### ISSUE TITLE
Unhandled error when trying to load blog post

### ISSUE THREAD

**Issue by blackmesacode** [fingers10/ILoveDotNetFunctionalTest#1]
Hi!

this might not be the ideal repo to bring up this issue, but it didnt find another way to get in contact with you.
trying to access https://ilovedotnet.org/blogs/enterprise-design-pattern-unit-of-work/?utm_source=newsletter.csharpdigest.net&utm_medium=referral&utm_campaign=building-pipelines-with-iasyncenumerable

gets me the following error:

![image](https://github.com/user-attachments/assets/2a3c325f-bc99-4304-ba57-2f9a3232e1b5)

![image](https://github.com/user-attachments/assets/99ae90ab-e1ae-4f3b-b243-9d149b820897)

**Comment by fingers10** [comment]
Hi @stephansum ,

Many thanks for bringing this to my notice.

I tried accessing the page from https://ilovedotnet.org/blogs/enterprise-design-pattern-unit-of-work and it's working fine. Looks like then URL you has shared has some issue because of query string parameters.

I'd recommend you to directly access I love dotnet from https://ilovedotnet.org 

Going forward you can contact me or you can raise issues from official i love dotnet repo - https://github.com/ILoveDotNet/ilovedotnet/issues

Thanks

**Comment by blackmesacode** [comment]
can confirm - without query params its working fine 👍thx for your reply.
